### PR TITLE
Disable online mode

### PR DESCRIPTION
**Pull request by saxnbt**
There will be no more targeted spambotting, allows people to join under alternative accounts without hassle again.

### CODE REVIEW

**Comment by IuCC123** [comment]
Please merge this since this has been going on for a while now! 👍🏼

**Comment by business-goose** [comment]
no don't do it

**Comment by TFTWPhoenix** [comment]
would be nice to have offline mode off again

**Comment by IuCC123** [comment]
> no don't do it

why not?

**Comment by LunaWasFlaggedAgain** [comment]
Bump @kaboombot

**Comment by business-goose** [comment]
> > no don't do it
> 
> why not?

much more calmer with online mode

**Comment by LunaWasFlaggedAgain** [comment]
> Someone is still attempting to send spambots to the server all day, as we speak.

I believe that is KCB.

**Comment by LunaWasFlaggedAgain** [comment]
> > Someone is still attempting to send spambots to the server all day, as we speak.
> 
> I believe that is KCB.

Yes, KCB and bartoszm77's nameclaimer are rejoining every 5 seconds.

**Comment by IuCC123** [comment]
Yeah. May it please be offline mode again? This will help us develop bots on the main server

**Pull request merged**
