### PR TITLE
Upgrade to Purpur 1.18.2 (closes #49)

### LINKED ISSUE #49: Update paper to 1.18
I think it would be great to upgrade kaboom to use the latest version of paper which may be better for the server.

### PR DESCRIPTION
**Pull request by allinkdev**

### CODE REVIEW

**Comment by business-goose** [comment]
FAWE works fine.

**Comment by win20-official** [comment]
Purpur is better than paper

**Comment by business-goose** [comment]
One important caveat to this upgrade is that usernames with section signs are no longer permitted, even in the vanilla server.
However, luckily, /nick and /username exist so this shouldn't affect people that much but I think everyone should be informed of this change.

**Comment by allinkdev** [comment]
> Maybe Purpur is different and has stood the test of time, but I haven't had a good experience with Paper forks in the past. Not too thrilled about an extra config file with irrelevant options for behavior.

In my experience the extra config file purpur uses doesn't affect me.

**Pull request closed without merging**
